export interface IStock{
    ActiveReason: string,
    ActiveReasonId: string,
    Attachment: string,
    BridalEvent_InBridal: string,
    BridalItemId: string,
    BridalItem_Description: string,
    BridalTypeItem: string,
    BridalTypeItemId: string,
    Color: string,
    ColorId: string,
    CommentBridalItem: string,
    Condition: string,
    ConditionId: string,
    Currency: string,
    CurrencyId: string,
    EndDate: string,
    IsActive: string,
    Location: string,
    Mct: string,
    NeedsCleaning: string,
    PositionBridalItem: string,
    Price: string,
    Size: string,
    SizeId: string,
    StartDate: string,
    StatusActive: string,
    StatusActiveDesc: string,
    StockBridalItemComment: string,
    StockBridalItemId: string,
    Style: string,
    StyleId: string,
    counter: string,
    lengthItem: string
}  

